x-mariadb-variables: &mariadb-variables
  image: mariadb:11.4
  platform: linux/amd64
  user: root
  environment:
    - MYSQL_ROOT_HOST=%
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=no
    - MYSQL_DATABASE=dbtest
    - MARIADB_AUTO_UPGRADE=1
    - TZ=UTC
  working_dir: /root  
  healthcheck:
      test: ["CMD", "bash", "-c", "mariadb -uroot -proot -e 'SHOW STATUS LIKE \"wsrep_cluster_status\"' | grep Primary"]
      interval: 10s
      retries: 5
      timeout: 5s

services:

  galera1:
    <<: *mariadb-variables
    container_name: galera1
    hostname: galera1
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=dbtest
      - WSREP_CLUSTER_NAME=vettabase_galera
      - WSREP_CLUSTER_ADDRESS=gcomm://galera1:4567,galera2:4567,galera3:4567
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.11
    ports:
      - "3301:3306"
    volumes:
      - "./volumes/galera1:/var/lib/mysql"
      - "./config/mysqld.conf:/etc/mysql/mariadb.conf.d/mysqld.cnf:ro"
      - "./config/mysql-client.cnf:/etc/.my.cnf"
      - "./scripts/sql:/tmp/sql"
      - "./scripts/bash/entrypoint_galera1.sh:/entrypoint.sh"
      - "./scripts/bash/init_galera1_users.sh:/docker-entrypoint-initdb.d/init_galera1_users.sh"
      - "./scripts/bash/init_galera1_db.sh:/docker-entrypoint-initdb.d/init_galera1_db.sh"
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "bash", "-c", "mariadb -uroot -proot -e 'SHOW STATUS LIKE \"wsrep_cluster_status\"' | grep Primary"]
      interval: 10s
      retries: 5
      timeout: 5s

  galera2:
    <<: *mariadb-variables
    container_name: galera2
    hostname: galera2
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.12
    ports:
      - "3302:3306"
    volumes:
      - "./volumes/galera2:/var/lib/mysql"
      - "./config/mysqld.conf:/etc/mysql/mariadb.conf.d/mysqld.cnf:ro"
      - "./config/mysql-client.cnf:/etc/.my.cnf"
      - "./scripts/sql:/tmp/sql"
      - "./scripts/bash/init_galera1_users.sh:/docker-entrypoint-initdb.d/init_galera1_users.sh"
    command:
      [
        "--binlog_format=ROW",
        "--wsrep_provider=/usr/lib/galera/libgalera_smm.so",
        "--wsrep_on=ON",
        "--wsrep_auto_increment_control=on",
        "--wsrep_cluster_name=vettabase_galera",
        "--wsrep_node_name=galera2",
        "--wsrep_cluster_address=gcomm://galera1:4567,galera2:4567,galera3:4567",
        "--wsrep_node_address=172.20.1.12",
        "--wsrep_sst_method=rsync",
      ]
    depends_on:
      galera1:
        condition: service_healthy        

  galera3:
    <<: *mariadb-variables
    container_name: galera3
    hostname: galera3
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.13
    ports:
      - "3303:3306"
    volumes:
      - "./volumes/galera3:/var/lib/mysql"
      - "./config/mysqld.conf:/etc/mysql/mariadb.conf.d/mysqld.cnf:ro"
      - "./config/mysql-client.cnf:/etc/.my.cnf"
      - "./scripts/sql:/tmp/sql"
      - "./scripts/bash/init_galera1_users.sh:/docker-entrypoint-initdb.d/init_galera1_users.sh"
    command:
      [
        "--binlog_format=ROW",
        "--wsrep_provider=/usr/lib/galera/libgalera_smm.so",
        "--wsrep_on=ON",
        "--wsrep_auto_increment_control=on",
        "--wsrep_cluster_name=vettabase_galera",
        "--wsrep_node_name=galera3",
        "--wsrep_cluster_address=gcomm://galera1:4567,galera2:4567,galera3:4567",
        "--wsrep_node_address=172.20.1.13",
        "--wsrep_sst_method=rsync",
      ]
    depends_on:
      galera2:
        condition: service_healthy

  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    hostname: haproxy
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.14
    ports:
      - "3310:8080"  # Web Admin Interface
      - "3311:3307"  # SQL Proxy (Load-Balanced Galera)
    volumes:
      - "./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    depends_on:
      galera1:
        condition: service_healthy
      galera2:
        condition: service_healthy
      galera3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "[ -S /tmp/haproxy.sock ]"]
      interval: 10s
      retries: 5
      timeout: 5s

  proxysql:
    container_name: proxysql
    hostname: proxysql
    image: proxysql/proxysql:2.7.2
    platform: linux/amd64
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.15
    ports:
      - "3320:6032"  # Admin Interface
      - "3321:6033"  # Write Queries (Hostgroup 10)
      - "3322:6033"  # Read Queries (Hostgroup 20)
    volumes:
      - "./config/proxysql.cnf:/etc/proxysql.cnf:ro"
    depends_on:
      galera1:
        condition: service_healthy
      galera2:
        condition: service_healthy
      galera3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "[ $(grep -c '^Name:[[:space:]]*proxysql' /proc/1/status) -gt 0 ]"]
      interval: 10s
      retries: 5
      timeout: 5s

  sysbench:
    image: custom-sysbench:1.1.0
    container_name: sysbench
    hostname: sysbench
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.16
    command: ["sleep", "infinity"]
    depends_on:
      proxysql:
        condition: service_healthy
      haproxy:
        condition: service_healthy
    environment:
      MYSQL_HOST_GALERA1: 172.20.1.11
      MYSQL_HOST_GALERA2: 172.20.1.12
      MYSQL_HOST_GALERA3: 172.20.1.13
      MYSQL_HOST_HAPROXY: 172.20.1.14
      MYSQL_HOST_PROXYSQL: 172.20.1.15
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT_GALERA: 3306
      MYSQL_PORT_HAPROXY: 3307
      MYSQL_PORT_PROXYSQL: 6033
      MYSQL_DB: dbtest

networks:
  vettabase_net:
    name: vettabase_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24