x-mariadb-variables: &mariadb-variables
  image: mariadb:11.4
  platform: linux/amd64
  user: root
  environment:
    - MYSQL_ROOT_HOST=%
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=no
    - MYSQL_DATABASE=sakila
    - WSREP_ON=ON
    - WSREP_PROVIDER=/usr/lib/galera/libgalera_smm.so
    - WSREP_SST_METHOD=rsync
    - WSREP_CLUSTER_NAME=vettabase_galera
    - BINLOG_FORMAT=ROW
    - DEFAULT_STORAGE_ENGINE=InnoDB
    - LOG_BIN=ON
    - LOG_REPLICA_UPDATES=ON
    - PID_FILE=/var/lib/mysql/mysqld.pid
  networks:
    vettabase_net:
      ipv4_address: 172.20.1.11
  healthcheck:
    test: ["CMD", "mariadb-admin", "--defaults-file=/etc/.my.cnf", "ping"]
    interval: 10s
    retries: 5
    timeout: 5s

services:

  galera1:
    <<: *mariadb-variables
    container_name: galera1
    hostname: galera1
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.11
    ports:
      - "3301:3306"
    volumes:
      - "./volumes/galera1_data:/var/lib/mysql"
      - "./config/mysql-client.cnf:/etc/.my.cnf"
      - "./scripts/sql:/tmp/sql"
      - "./scripts/bash/init_galera1.sh:/docker-entrypoint-initdb.d/init_galera1.sh"
      - "./scripts/bash/init_users.sh:/docker-entrypoint-initdb.d/init_users.sh"
    command:
      [
        "--server-id=1",
        "--wsrep_cluster_address=gcomm://",
        "--wsrep_node_address=172.20.1.11"
      ]

  galera2:
    <<: *mariadb-variables
    container_name: galera2
    hostname: galera2
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.12
    ports:
      - "3302:3306"
    volumes:
      - "./volumes/galera2_data:/var/lib/mysql"
      - "./config/mysql-client.cnf:/etc/.my.cnf"
      - "./scripts/sql:/tmp/sql"
      - "./scripts/bash/init_users.sh:/docker-entrypoint-initdb.d/init_users.sh"
    command:
      [
        "--server-id=2",
        "--wsrep_cluster_address=gcomm://galera1,galera2,galera3",
        "--wsrep_node_address=172.20.1.12"
      ]
    depends_on:
      galera1:
        condition: service_healthy

  galera3:
    <<: *mariadb-variables
    container_name: galera3
    hostname: galera3
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.13
    ports:
      - "3303:3306"
    volumes:
      - "./volumes/galera3_data:/var/lib/mysql"
      - "./config/mysql-client.cnf:/etc/.my.cnf"
      - "./scripts/sql:/tmp/sql"
      - "./scripts/bash/init_users.sh:/docker-entrypoint-initdb.d/init_users.sh"
    command:
      [
        "--server-id=3",
        "--wsrep_cluster_address=gcomm://galera1,galera2,galera3",
        "--wsrep_node_address=172.20.1.12"
      ]
    depends_on:
      galera1:
        condition: service_healthy

  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    hostname: haproxy
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.14
    ports:
      - "3310:8080"  # Web Admin Interface
      - "3311:3307"  # SQL Proxy (Load-Balanced Galera)
    volumes:
      - "./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    depends_on:
      galera1:
        condition: service_healthy
      galera2:
        condition: service_healthy
      galera3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "[ -S /tmp/haproxy.sock ]"]
      interval: 10s
      retries: 5
      timeout: 5s

  proxysql:
    container_name: proxysql
    hostname: proxysql
    image: proxysql/proxysql:2.7.2
    platform: linux/amd64
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.15
    ports:
      - "3320:6032"  # Admin Interface
      - "3321:6033"  # Write Queries (Hostgroup 10)
      - "3322:6033"  # Read Queries (Hostgroup 20)
    volumes:
      - "./config/proxysql.cnf:/etc/proxysql.cnf:ro"
    depends_on:
      galera1:
        condition: service_healthy
      galera2:
        condition: service_healthy
      galera3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "[ $(grep -c '^Name:[[:space:]]*proxysql' /proc/1/status) -gt 0 ]"]
      interval: 10s
      retries: 5
      timeout: 5s

  sysbench:
    image: custom-sysbench:1.1.0
    container_name: sysbench
    hostname: sysbench
    networks:
      vettabase_net:
        ipv4_address: 172.20.1.16
    command: ["sleep", "infinity"]
    depends_on:
      proxysql:
        condition: service_healthy
      haproxy:
        condition: service_healthy
    volumes:
      - "./volumes/benchmark_data:/tmp/benchmark_data"
    environment:
      MYSQL_HOST_GALERA1: 172.20.1.11
      MYSQL_HOST_GALERA2: 172.20.1.12
      MYSQL_HOST_GALERA3: 172.20.1.13
      MYSQL_HOST_HAPROXY: 172.20.1.14
      MYSQL_HOST_PROXYSQL: 172.20.1.15
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 6033
      MYSQL_DB: sakila

networks:
  vettabase_net:
    name: vettabase_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24